project:
  type: website
  output-dir: docs
  resources:
    - files/**

website:
  title: "Mainak Bardhan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
      

format:
  html:
    theme: cosmo
    
    css: styles.css
    toc: true
    page-layout: full



 